// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxi-4BrHlSVRHXk5oUXng62acvlN9on-U',
    appId: '1:727492526162:web:0ace2e793815eabe05df8b',
    messagingSenderId: '727492526162',
    projectId: 'inventory-app-5e602',
    authDomain: 'inventory-app-5e602.firebaseapp.com',
    storageBucket: 'inventory-app-5e602.appspot.com',
    measurementId: 'G-JQZR1SK34Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQkwszR_cGO9ouhuS2on6IMD2zGbFj-ec',
    appId: '1:727492526162:android:a57efbb07605f95e05df8b',
    messagingSenderId: '727492526162',
    projectId: 'inventory-app-5e602',
    storageBucket: 'inventory-app-5e602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpgSz5QuUpwXYqNyYt6SytR2Kmq9Br7A8',
    appId: '1:727492526162:ios:b45e6acf76a292f005df8b',
    messagingSenderId: '727492526162',
    projectId: 'inventory-app-5e602',
    storageBucket: 'inventory-app-5e602.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpgSz5QuUpwXYqNyYt6SytR2Kmq9Br7A8',
    appId: '1:727492526162:ios:b45e6acf76a292f005df8b',
    messagingSenderId: '727492526162',
    projectId: 'inventory-app-5e602',
    storageBucket: 'inventory-app-5e602.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxi-4BrHlSVRHXk5oUXng62acvlN9on-U',
    appId: '1:727492526162:web:e40925c326265c1c05df8b',
    messagingSenderId: '727492526162',
    projectId: 'inventory-app-5e602',
    authDomain: 'inventory-app-5e602.firebaseapp.com',
    storageBucket: 'inventory-app-5e602.appspot.com',
    measurementId: 'G-EPBZGYT2WE',
  );
}
